### ISSUE TITLE
Files from Fire Emblem Warriors Three Hopes Demo cannot be extracted at all

### ISSUE THREAD

**Issue by Andree12** [healingbrew/Cethleann#52]
Input:
`Cethleann.DataExporter.exe --zhao --platform Switch *output folder* *Three Hopes folder* `
Output:
```
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt64(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int64.Parse(String s, NumberStyles style)
   at Cethleann.Archive.RDB.DecodeOffset(String packed) in C:\projects\cethleann\Cethleann\Archive\RDB.cs:line 284
   at Cethleann.Archive.RDB..ctor(Span`1 buffer, String name, String directory) in C:\projects\cethleann\Cethleann\Archive\RDB.cs:line 63
   at Cethleann.ManagedFS.Nyotengu.AddDataFS(String path) in C:\projects\cethleann\Cethleann\ManagedFS\Nyotengu.cs:line 84
   at Cethleann.DataExporter.Program.Main(String[] args) in C:\projects\cethleann\Cethleann.DataExporter\Program.cs:line 50
```
[FEWTH Demo files.zip](https://github.com/yretenai/Cethleann/files/8865425/FEWTH.Demo.files.zip)

**Comment by neptuwunium** [comment]
Fixed, use --rdb (--zhao, --nyotengu, etc is gone)
